volumes:
  ssh-data:

networks:
  dokploy-network:
    external: true

services:
  scalelite-proxy:
    image: ${NGINX_DOCKER_IMAGE:-nginx:1.28}
    restart: unless-stopped
    networks:
      - dokploy-network
      - default
    expose:
      - 80
      - 443
    environment:
      - NGINX_HOSTNAME=${SL_HOST:-sl.xlab.blindside-ps.dev}
      - SL_API_HOST=${SL_API_HOST:-scalelite-api:3000}
      - SL_RECORDINGS_HOST=${SL_RECORDINGS_HOST:-scalelite-recordings:80}
    volumes:
      - /var/log/${HASH}/scalelite-proxy:/var/log/nginx
      - ./data/proxy/nginx/sites.template.${DOCKER_PROXY_NGINX_TEMPLATE:-scalelite-proxy}:/etc/nginx/sites.template
      - ./data/proxy/nginx/sites-common:/etc/nginx/sites-common
    depends_on:
      - scalelite-api
      - scalelite-recordings
    command: /bin/bash -c "envsubst '$$NGINX_HOSTNAME $$SL_API_HOST $$SL_RECORDINGS_HOST' < /etc/nginx/sites.template > /etc/nginx/conf.d/default.conf && while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g 'daemon off;'"

  scalelite-recordings:
    image: ${SCALELITE_RECORDINGS_DOCKER_IMAGE:-bigbluebutton/bbb-playback-proxy:focal-260-alpine}
    restart: unless-stopped
    volumes:
      - /var/log/${HASH}/scalelite-recordings:/var/log/nginx
      - ${SCALELITE_RECORDING_DIR:-/mnt/scalelite-recordings/var/bigbluebutton}/published:/var/bigbluebutton/published
    depends_on:
      - scalelite-api
    networks:
      - default

  scalelite-api:
    image: ${SCALELITE_DOCKER_IMAGE:-blindsidenetwks/scalelite:v1.6.5}
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - DATABASE_URL=${DATABASE_URL:-postgres://postgres:password@postgres:5432/scalelite?pool=5}
      - RECORDING_DISABLED=${RECORDING_DISABLED:-false}
      - SERVER_ID_IS_HOSTNAME=${SERVER_ID_IS_HOSTNAME:-false}
      - RAILS_LOG_TO_STDOUT=${RAILS_LOG_TO_STDOUT:-false}
    volumes:
      #- /var/log/${HASH}/scalelite-api:/srv/scalelite/log
      - ${SCALELITE_RECORDING_DIR:-/mnt/scalelite-recordings/var/bigbluebutton}:/var/bigbluebutton
    logging:
      driver: journald
    networks:
      - dokploy-network
      - default

  scalelite-poller:
    image: ${SCALELITE_DOCKER_IMAGE:-blindsidenetwks/scalelite:v1.6.5}
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - SERVER_ID_IS_HOSTNAME=${SERVER_ID_IS_HOSTNAME:-false}
      - RAILS_LOG_TO_STDOUT=${RAILS_LOG_TO_STDOUT:-false}
    volumes:
      - /var/log/${HASH}/scalelite-poller:/app/log
    command: /bin/sh -c "bin/start-poller"
    depends_on:
      - scalelite-api
    logging:
      driver: journald
    networks:
      - dokploy-network
      - default

  scalelite-recording-importer:
    image: ${SCALELITE_DOCKER_IMAGE:-blindsidenetwks/scalelite:v1.6.5}
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - DATABASE_URL=${DATABASE_URL:-postgres://postgres:password@postgres:5432/scalelite?pool=5}
      - RECORDING_DISABLED=false
      - RAILS_LOG_TO_STDOUT=${RAILS_LOG_TO_STDOUT:-false}
    volumes:
      - /var/log/${HASH}/scalelite-recording-importer:/app/log
      - ${SCALELITE_RECORDING_DIR:-/mnt/scalelite-recordings/var/bigbluebutton}:/var/bigbluebutton
      - ${SCALELITE_RECORDING_DIR:-/mnt/scalelite-recordings/var/bigbluebutton}/spool:/var/bigbluebutton/spool
    command: /bin/sh -c "bin/start-recording-importer"
    depends_on:
      - scalelite-api
    logging:
      driver: journald
    networks:
      - dokploy-network
      - default

  scalelite-ssh:
    image: lscr.io/linuxserver/openssh-server:latest
    restart: unless-stopped
    environment:
      - PUID=${SSH_PUID:-1000}
      - PGID=${SSH_PGID:-1000}
      - TZ=${TZ:-UTC}
      - PASSWORD_ACCESS=${SSH_PASSWORD_ACCESS:-false}
      - SUDO_ACCESS=${SSH_SUDO_ACCESS:-false}
      - USER_NAME=${SSH_USER_NAME:-bigbluebutton}
      - LOG_STDOUT=${SSH_LOG_STDOUT:-true}
      - PUBLIC_KEY_DIR=${SSH_PUBLIC_KEY_DIR:-/public-keys}
    volumes:
      - ssh-data:/config
      - ../files/keys:/public-keys
      - ./data/ssh/scripts:/custom-cont-init.d:ro
      - ${SCALELITE_RECORDING_DIR:-/mnt/scalelite-recordings/var/bigbluebutton}:/mnt/scalelite-recordings/var/bigbluebutton
    ports:
      - ${SL_SSH_PORT:-2222}:2222